### PR TITLE
[WIP] Add support for Listing/Creating/Deleting roles, groups

### PR DESCRIPTION
**Pull request by lindgrenj6**
This PR is adding support for the following operations:
- list, create, delete roles
- list, create, delete groups
- adding users to groups
- adding roles to groups

\# TODO:
- [ ]  add support for using a PSK on the client for create/delete operations

### CODE REVIEW

**Comment by lphiri** [comment]
@lindgrenj6  I am curious about this PR. Typically these additional APIs are only needed by the RBAC service itself, and not clients. What is the anticipated use case for these?
Also I believe we plan to sunset/deprecate the policies API
cc @coderbydesign

**Comment by lindgrenj6** [comment]
Basically in order to support user-level sources we're going to be creating custom-roles. in a single group which we're going to create programmatically. That way we can limit the views of those individual source records to the people that created them.

If we're deprecating the policies api - what is the plan there? Is there going to be a new way to add a role to a group?

**Comment by lindgrenj6** [comment]
Actually - I may not need the policy part, I can just add the role directly! I didn't know that. I was thinking too much like Amazon IAM where you have to bind the role to the policy haha

**Comment by lphiri** [comment]
I see, what does this mean in terms on the number of dynamic groups you are going to create and impact on UX.
I assume there is no way we can express this in the default groups we already have @coderbydesign.
Also @lindgrenj6  is there a reason we need RBAC for this usecase instead of just doing a simple "owner" check. I believe this is what we do in Remediations today.

**Comment by coderbydesign** [comment]
> I can just add the role directly!
Correct @lindgrenj6 :) - groups have policies, and policies have roles, but we've obfuscated the policies and just have one policy per group that we programmatically create under the hood. This was a decision made early on, to not surface/require policies be managed directly.

> I assume there is no way we can express this in the default groups we already have @coderbydesign.
@lphiri since these are dynamic, not at the moment. I did talk with Jacob and Drew about the possibility of exploring system default groups which could be managed in seeds as well.

**Comment by lindgrenj6** [comment]
Closing this since we ended up changing directions. Maybe in the future we can use this if someone wants to use these features.

**Pull request closed without merging**
